name: PR Check

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TEST: abc.def

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: List env variables
      run: env