name: Update Commit Message

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  update_commit_message:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch the entire history to enable rebase

      - name: Set Git configuration
        run: |
          git config --global user.email "phan.tthinh1@gmail.com"
          git config --global user.name "Thinh Phan"

      - name: Rebase the merged commit onto the main branch
        run: |
          git checkout main
          git pull origin main
          git rebase origin/main

      - name: Amend the commit message to include PR number
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          NEW_MESSAGE="$(git log -1 --pretty=%B) (#${PR_NUMBER})"

          # Update the commit message using git commit --amend
          git commit --amend -m "$NEW_MESSAGE"
          git push origin main --force
